In [2]:
import torch

In [6]:
# simple Tensor
x = torch.Tensor(3, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# tensor with random values
y = torch.rand(2,2)
y

tensor([[0.4934, 0.9369],
        [0.7824, 0.7264]])

In [7]:
# basic math operations with tensors
x = torch.ones(2,2)
y = torch.ones(2,2) * 4
x + y

tensor([[5., 5.],
        [5., 5.]])